[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@uniswap/v2-periphery/=lib/v2-periphery/',
    '@reactive/=lib/reactive-lib/'
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC}"